### ISSUE TITLE
Suggestion: Make this a book/HTML with the Rust project `mdbook`

### ISSUE THREAD

**Issue by BenEdridge** [Dhghomon/easy_rust#11]
Great work, do you have any thoughts on making this a website with the Rust project [mdbook](https://github.com/rust-lang/mdBook) by converting markdown -> html and hosting on GitHub pages?

`mdbook` allows you to invoke the Rust Playground directly, provides search and organisation of pages plus a number of other cool features.

I'm happy to contribute a PR 😄

**Comment by Dhghomon** [comment]
@BenEdridge I assumed that I would eventually get around to that but haven't looked into it yet as I'm not familiar with implementing mdbook yet. Somebody else already ported it to that format this morning: https://twitter.com/conikeec/status/1286083549842440194 But does that mean that any changes I make to the readme file now will get ported as well? Or does it have to be redone manually?

For the writing (which is still ongoing) I prefer to have everything in a single page but if an mdbook version could get automatically generated from the changes I make to the one file then that would be great. Otherwise then I guess we would have to wait until it reaches some sort of stability first?

So yeah, whatever is technically doable without me having to move away from the single file for editing would certainly be fine.

**Comment by stappersg** [comment]
> I'm happy to contribute a PR smile

_Just do it_

**Comment by nisrulz** [comment]
I really like what you have done with this book and thank you for writing it. I was looking for something like this. 

I am curious why do you prefer to write it in the single file.

Is it a preference because it helps you focus on the writing?

(Please don't take this question as disrespecting your hard work or choices you make as an author, I am thinking more on the side how we can get it bundled as a proper book which mdBook provides. If you choose to write in a single file, I am sure it is not a problem. The content is what matters and you have done a really good job on that part 😸 )

...or is it about being able to print it as a book? 

If it is about being able to print it as a single book, mdBook actually does that even though you write each chapters in a single markdown file. When you do hit the print icon in the published mdBook html version, you get all pages joined and the book ready to be printed out. I can help setup a CI to build the book and publish it whenever you make changes in the chapters (markdown files).

**Comment by Dhghomon** [comment]
@nisrulz No problem about the questions! Yes, it's mostly a personal style when it comes to writing. I love having everything in a single page to scroll through. But since you say that I can keep writing in a single markdown file and then quickly export to mdBook, it should be no problem. Although that would require waiting until the original file is mostly stabilized, correct? Or is there an option like just clicking "update MdBook" every time I make an edit to the main file that will re-export it? I see it says that it caches versions so it doesn't have to re-update the whole thing every time.

Ideally at the end I would like a setup that starts out with the whole single page (as it is currently) and a link right at the top saying to click there if the reader prefers mdBook format, and then we can have the best of both worlds.

Also, is this https://twitter.com/conikeec/status/1286083549842440194 the exact format you are talking about?

**Comment by nisrulz** [comment]
@Dhghomon Got it! In that case there is no direct work around 😅 

Yes, the same as per that tweet. The files are split when you are writing into each chapter. However since you want to have a single file for writing, then mdBook setup will not work directly for you. mdBook forces you to write each chapter in a individual markdown file.

However say if I wanted to solve this in a way that allows you to continue writing in a single file but also spit out a mdBook version as you write it, I was thinking of writing a bash script. The script would basically read the content of the single markdown file, split it into chapters everytime it finds a "Heading" in the single file and then save it in a file structure mdBook requires. Then on your side you actually follow the same steps as you do today. However when you push a commit with changes to your single markdown file, the CI kicks in to do all the steps of running the script, creating mdbook format and publishing it to to Github Pages.

I looks like it is doable, so I will get back to you when I have something that can do that.

Again, thank you for answering my question and also for writing this book. I am sure this is going to be helpful to many 😸

**Comment by Dhghomon** [comment]
All done now! Here's what it looks like: https://dhghomon.github.io/easy_rust/Chapter_6.html
