### ISSUE TITLE
use Verbs instead of Nouns for trait examples

### ISSUE THREAD

**Issue by pretzelhammer** [Dhghomon/easy_rust#16]
Rust is not an OOP language and does not support OOP patterns. There's a [good thread about this on the Official Rust Users forum](https://users.rust-lang.org/t/why-dont-we-call-rust-behavior-oriented-programming/37777) where people suggest calling Rust a Behavior-Oriented Programming language so as to clearly distinguish it from OOP.

I'd like to point out that all the traits in the standard library can be easily mapped to verbs or actions like:

- `Display` means the type is _displayable_
- `Copy` means the type is _copyable_
- `Iterator` means the type is _iterable_
- and so on

In your document you use `trait Dog` as an example which kinda makes sense in an OOP-sense but not really in a BOP-sense since what verb or action does a noun like `Dog` map to? If a type implements `Dog` it's _barkable_, _walkable_, _pettable_? I'd argue all of those properties should be their own traits. I know the whole Animal thing is a super popular example in OOP languages so it's tempting to re-use it to try to explain Rust traits but I think it's generally more misleading than helpful as it reinforces the misconception that Rust is OOP.

I can't tell you off the top of my head what would be a better example but just anything where the trait name is a Verb and not a Noun would be better.

**Comment by Dhghomon** [comment]
I've never really done anything in any OOP language so it's definitely not interference from that, but now that I think about it, the idea must have come from having read this: https://doc.rust-lang.org/book/ch19-03-advanced-traits.html

It has the following phrase:

`The Dog type also implements the trait Animal, which describes characteristics that all animals have.`

...which could then turn into something like the following as we go down the chain of things related to other things:

`The Terrier type also implements the trait Dog, which describes characteristics that all dogs have.`

`The AireDaleTerrier type also implements the trait Terrier, which describes characteristics that all terriers have.`

That said, I suppose a lot of people would be coming from OOP languages so I can give some thought to a better trait that would do a good job making the point you just described. Explaining them as (mostly?) verbs is a good idea too.

Although on the subject of animal, animal is originally an adjective (from the word for soul) and in Korean adjectives and verbs are almost the same thing! So maybe animal found its way into the example by virtue of that feel of connection between the two.

**Comment by pretzelhammer** [comment]
I think that section of the book was written to appeal to the OOP crowd and isn't necessarily a good representation of how one should actually think about and use Rust traits. Here's a [good example from the std docs for the Ord trait](https://doc.rust-lang.org/std/cmp/trait.Ord.html#how-can-i-implement-ord) of something you can do with Rust traits that makes no sense in an OOP-context. Despite the fact that `Ord` requires `PartialOrd` it's actually `PartialOrd`'s implementation that defers to `Ord`! If we use `Dog` in place of `Ord` and `Animal` in place of `PartialOrd` it'd be like if `Animal` secretly used `Dog` methods internally which is just... very confusing. Hence I don't think it's good practice to try to develop some "noun hierarchy" with traits and instead traits should be treated as verbs.

**Comment by sudo-nice** [comment]
>Rust is not an OOP language and does not support OOP patterns.

This seems to be a tricky matter. To quote https://doc.rust-lang.org/stable/book/ch17-01-what-is-oo.html
![scr](https://i.imgur.com/Iu3fU5f.png)

---

>Display means the type is displayable
>Copy means the type is copyable
>Iterator means the type is iterable

I'm a newbie to Rust, but those "displayable", "copyable" and "iterable" do remind me of roles in Ruby. And Ruby is pretty much an OOP language. So, maybe it's OK to use some OOP style in Rust.

**Comment by Dhghomon** [comment]
Something else came to mind in this discussion about verbs and adjectives, which to my mind feel a bit verb-y:

https://doc.rust-lang.org/stable/rust-by-example/generics/bounds/testcase_empty.html

That's an example I remember about using traits as bounds (no functionality), and there they are all adjectives. And in Korean adjectives are also very verb-y, both in feel and usage in that they end in -da just like all verbs do. So that got me thinking about the relationship between the two:

`impl Red for Cardinal` Being red is actually the same as "emitting red light" (or absorbing everything except the red part of the spectrum, rather)

Being *cold* means to *emanate heat*, being *afraid* means to *feel terror*, *beautiful* means to *have* a pleasant appearance, etc. etc.

Meanwhile nouns can't do that except for the verb *to be*: a *rock* is just being a rock, a flower is just being a flower, etc. And the `Animal` example above kind of gets a free pass due to animal having an adjectival feel?

On top of that are traits like Into and From which have an implied verb: CreateInto(?) or BeCreatedFrom...

So how about explaining that traits are for verbs and verb-y things? I think that could work to explain how they work while not getting a new user thinking that a trait absolutely must be attached to a verb.

**Comment by Dhghomon** [comment]
I have an idea already for a better trait example that I'll have up in a day or two. Won't talk about it here because it's going to be a surprise!

**Comment by Dhghomon** [comment]
A month late, but I finally added to the trait section with an RPG-type thing and some comments on behaviour and verby-type stuff.
