### ISSUE TITLE
Suggestion: make each snippet compilable

### ISSUE THREAD

**Issue by AlexanderWillner** [Dhghomon/easy_rust#32]
Suggestion: I suggest that each of the over 300 code snippet should be compilable (besides those that fail on purpose).

Approach: I wrote a preliminary little script to extract the snippets: ```cargo install md2src && md2src && for snippet in $(ls code*.rs); do rustc $snippet ; done```. This shows a number of issues and some snippets should be annotated with something like ```#[doc = "This will fail."]```.

**Comment by Dhghomon** [comment]
Q: Is there any way to write the script so that it only pulls in snippets that successfully compile? The examples so far that don't compile are always followed up by slightly modified versions that do work so it would be best if they didn't show up at all.

Annotating with `#[doc = "This will fail."]` could also look intimidating to a new user and would require explanation. Unless it can be hidden, of course. Or maybe set up the script so that it gets added to the top when a snippet doesn't compile?

**Comment by AlexanderWillner** [comment]
Any string could be used. E.g. `// this doesn’t compile`
